---
kind: Service
apiVersion: v1
metadata:
  name: app-1-service
spec:
  selector:
    app: app-1
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        envFrom:
          - configMapRef:
              name: game-cm
        ports:
        - containerPort: 80