---
kind: Service
apiVersion: v1
metadata:
  name: app-2-service
spec:
  selector:
    app: app-2
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
spec:
  selector:
    matchLabels:
      app: app-2
  replicas: 1
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        env:
          - name: game-name
            valueFrom:
              configMapKeyRef:
                name: game-cm
                key: myconfig.yaml
          - name: player-name
            valueFrom:
              configMapKeyRef:
                name: game-cm
                key: player
        ports:
        - containerPort: 80
