---
kind: Service
apiVersion: v1
metadata:
  name: app-3-service
spec:
  selector:
    app: app-3
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-deployment
spec:
  selector:
    matchLabels:
      app: app-3
  replicas: 1
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        ports:
          - containerPort: 80
        volumeMounts:
          - name: app-config
            mountPath: /etc/config
      volumes:
        - name: app-config
          configMap:
            name: game-cm
            items:
              - key: player
                path: player

